/*
 * This file has been generated by squashql-codegen. The project is available here https://github.com/squashql/squashql-codegen
 */
import {TableField} from "@squashql/squashql-js"

export interface SquashQLTable {
    _fields: TableField[]
    _name: string
}

class Budget implements SquashQLTable {
    readonly _name = "budget"
    readonly incomeExpenditure: TableField = new TableField("budget.Income / Expenditure")
    readonly category: TableField = new TableField("budget.Category")
    readonly subcategory: TableField = new TableField("budget.Subcategory")
    readonly year: TableField = new TableField("budget.Year")
    readonly month: TableField = new TableField("budget.Month")
    readonly day: TableField = new TableField("budget.Day")
    readonly date: TableField = new TableField("budget.Date")
    readonly description: TableField = new TableField("budget.Description")
    readonly amount: TableField = new TableField("budget.Amount")
    readonly happinessScore: TableField = new TableField("budget.Happiness score")
    readonly scenario: TableField = new TableField("budget.Scenario")
    readonly _fields: TableField[] = [this.incomeExpenditure, this.category, this.subcategory, this.year, this.month, this.day, this.date, this.description, this.amount, this.happinessScore, this.scenario]
}

const budget = new Budget()

export {
    budget
}
