/*
 * This file has been generated by squashql-codegen. The project is available here https://github.com/squashql/squashql-codegen
 */
import {TableField} from "@squashql/squashql-js"

export interface SquashQLTable {
    _fields: TableField[]
    _name: string
}

class Spending implements SquashQLTable {
    readonly _name = "spending"
    readonly city: TableField = new TableField("spending.city")
    readonly country: TableField = new TableField("spending.country")
    readonly continent: TableField = new TableField("spending.continent")
    readonly spendingCategory: TableField = new TableField("spending.spending category")
    readonly spendingSubcategory: TableField = new TableField("spending.spending subcategory")
    readonly year: TableField = new TableField("spending.year")
    readonly amount: TableField = new TableField("spending.amount")
    readonly _fields: TableField[] = [this.city, this.country, this.continent, this.spendingCategory, this.spendingSubcategory, this.year, this.amount]
}

class Portfolio implements SquashQLTable {
    readonly _name = "portfolio"
    readonly ticker: TableField = new TableField("portfolio.Ticker")
    readonly dateScenario: TableField = new TableField("portfolio.DateScenario")
    readonly currency: TableField = new TableField("portfolio.Currency")
    readonly nbShares: TableField = new TableField("portfolio.NbShares")
    readonly riskType: TableField = new TableField("portfolio.RiskType")
    readonly scenarioValue: TableField = new TableField("portfolio.ScenarioValue")
    readonly _fields: TableField[] = [this.ticker, this.dateScenario, this.currency, this.nbShares, this.riskType, this.scenarioValue]
}

class Population implements SquashQLTable {
    readonly _name = "population"
    readonly country: TableField = new TableField("population.country")
    readonly continent: TableField = new TableField("population.continent")
    readonly population: TableField = new TableField("population.population")
    readonly _fields: TableField[] = [this.country, this.continent, this.population]
}

class Budget implements SquashQLTable {
    readonly _name = "budget"
    readonly incomeExpenditure: TableField = new TableField("budget.Income / Expenditure")
    readonly category: TableField = new TableField("budget.Category")
    readonly subcategory: TableField = new TableField("budget.Subcategory")
    readonly year: TableField = new TableField("budget.Year")
    readonly month: TableField = new TableField("budget.Month")
    readonly day: TableField = new TableField("budget.Day")
    readonly date: TableField = new TableField("budget.Date")
    readonly description: TableField = new TableField("budget.Description")
    readonly amount: TableField = new TableField("budget.Amount")
    readonly happinessScore: TableField = new TableField("budget.Happiness score")
    readonly scenario: TableField = new TableField("budget.Scenario")
    readonly _fields: TableField[] = [this.incomeExpenditure, this.category, this.subcategory, this.year, this.month, this.day, this.date, this.description, this.amount, this.happinessScore, this.scenario]
}

const spending = new Spending()
const portfolio = new Portfolio()
const population = new Population()
const budget = new Budget()

export {
    spending, portfolio, population, budget
}
