name: squashql-showcase ci

on:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress -DskipTests
      - name: Run tests
        run: mvn --no-transfer-progress test

  ts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install ts
        run: npm --prefix ts install
      - name: Build ts
        run: npm --prefix ts run build

  ui:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install ui
        run: npm --prefix ui install
      - name: Build ui
        run: npm --prefix ui run build

